# Generated by Django 5.2.7 on 2025-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
